import { type NextPage } from "next";
import { Form, Formik } from "formik";
import FormInput from "@/components/ui/form-input";
import { Button } from "@/components/ui/button";
import { useRouter } from "next/router";

const ForgotPassword: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <p className="text-lg font-bold lg:text-2xl">Forgot password</p>
      <p className="mt-1 text-brandgray">
        We&apos;ll send you a reset password link to your registered email
        address
      </p>
      <Formik
        onSubmit={(values, actions) => {
          actions.resetForm();
        }}
        initialValues={{ email: "" }}
      >
        <Form className="mt-7 w-full">
          <FormInput name="email" type="email" placeholder="Registered Email" />

          <Button className="mt-6 w-full">Email me a recovery link</Button>
          <Button
            onClick={() => {
              void (async () => {
                await router.push("/");
                
              })();
            }}
            variant={"outline"}
            className="mt-3 w-full"
          >
            Return to sign in
          </Button>
        </Form>
      </Formik>

      {/* <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        
      </main> */}
    </>
  );
};

export default ForgotPassword;
