import { type NextPage } from "next";
import Head from "next/head";
import { Form, Formik } from "formik";
import FormInput from "@/components/ui/form-input";
import { Button } from "@/components/ui/button";
import { useRouter } from "next/router";

import { api } from "@/utils/api";
import PasswordInput from "@/components/ui/password-input";

const Home: NextPage = () => {
  const context = api.useContext();
  const router = useRouter();

  const { mutate, isLoading } = api.auth.login.useMutation({
    onSuccess(data) {
      context.auth.user.setData(undefined, data);
    },
    // onError(error) {
      
    // },
    async onSettled(data) {
      if (data) {
        const redirect = (router.query.redirect as string) || '/app';
        await router.replace(redirect);
      }
    },
  })

  return (
    <>
      {/* <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Formik
          onSubmit={(values, actions) => {
            const { email, password } = values;
            mutate({
              email,
              password,
            });

            actions.resetForm(); 
          }}
          initialValues={{ email: "", password: "" }}
        >
          <Form>
            <FormInput name="email" type="email" placeholder="Email or Mobile Number" />
            <PasswordInput name="password" type="password" placeholder="Password" />

            <Button className="u-w-100">
              {"Login"}
            </Button>
          </Form>
        </Formik>
      </main> */}
    </>
  );
};

export default Home;
