import { type NextPage } from "next";
import Head from "next/head";
import { Form, Formik } from "formik";
import FormInput from "@/components/ui/form-input";
import { Button } from "@/components/ui/button";
import { useRouter } from "next/router";

import { api } from "@/utils/api";

const Register: NextPage = () => {
  const context = api.useContext();
  const router = useRouter();

  const users = api.auth.getAll.useQuery();

  const { mutate, isLoading } = api.auth.register.useMutation({
    onSuccess(data) {
      context.auth.user.setData(undefined, data);
    },
    // onError(error) {

    // },
    async onSettled(data) {
      if (data) {
        const redirect = (router.query.redirect as string) || "/app";
        await router.replace(redirect);
      }
    },
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Formik
          onSubmit={(values, actions) => {
            const { email, password, firstName, lastName, mobile } = values;
            mutate({
              email,
              password,
              firstName,
              lastName,
              mobile,
            });

            //actions.resetForm();
          }}
          initialValues={{
            email: "",
            password: "",
            firstName: "",
            lastName: "",
            mobile: "",
          }}
        >
          <Form>
            <FormInput name="firstName" type="text" label="First Name" />
            <FormInput name="lastName" type="text" label="Last Name" />
            <FormInput name="email" type="email" label="Email Address" />
            <FormInput name="mobile" type="text" label="Mobile Number" />
            <FormInput name="password" type="password" label="Password" />

            <Button className="u-w-100">{"Login"}</Button>
          </Form>
        </Formik>
      </main>
    </>
  );
};

export default Register;
